name: npm publish

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: npm install, test, and build
        run: |
          npm install
          npm test
          npm run-script build
      - name: npm publish
        run: |
          npm config set '//registry.npmjs.org/:_authToken' "${NPM_AUTH_TOKEN}"
          npm publish --access public
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
